mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ./test/support/db/seed:/docker-entrypoint-initdb.d
  working_dir: /var/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "itsasekret_85a96vbFdh"
    MYSQL_DATABASE: "senecatest"
